### ISSUE TITLE
Please add -txindex=1 to bitcoind start params.

### ISSUE THREAD

**Issue by artemii235** [dathbezumniy/btcdocker_regtest#1]
The `getrawtransaction` call fails with `No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.` if txindex is turned off.

**Comment by dth88** [comment]
enabled txindex, both calls getrawtransaction and gettransaction are working now.

**Comment by artemii235** [comment]
Super, thanks! Please add `#issue_id` to your commit messages, the Github will link the commit to issue and will be also useful for readers of your code to understand the context of changes you made.
E.g.: https://github.com/KomodoPlatform/atomicDEX-API/commit/e01d8acb0f05cf7ac6450f0956a2d69fda09a822

<img width="723" alt="Screenshot 2020-03-09 at 14 20 37" src="https://user-images.githubusercontent.com/15745003/76191137-3caa9600-6211-11ea-8106-a12a3fb837a5.png">
