### ISSUE TITLE
Reduce images size (especially flask).

### ISSUE THREAD

**Issue by artemii235** [dathbezumniy/btcdocker_regtest#2]
```
btcdocker_regtest_flask     929MB
btcdocker_regtest_node2     237MB
btcdocker_regtest_node1     237MB
```

929MB looks excessive for quite small task of periodical JSON RPC API invocation.
Please consider using Alpine based images: https://hub.docker.com/_/python?tab=tags&page=1&name=alpine, also maybe some of Python dependencies are not required and there're other reasons of the image to be so huge?

Also it might be useful to consider refactoring nodes Dockerfile using official best practices: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

**Comment by dth88** [comment]
thanks Artem, I'll look into it

**Comment by dth88** [comment]
lol, just changing to alpine based python reduced the size x7, now around 100MB for flask app
